# Generated by Django 3.1.1 on 2021-03-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_activity_activitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activitytype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.activitytype', verbose_name='Aktivitetstype'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.department', verbose_name='Afdeling'),
        ),
    ]
